name             'netplan'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures netplan'
source_url       'https://github.com/sous-chefs/netplan'
issues_url       'https://github.com/sous-chefs/netplan/issues'
chef_version     '>= 15.5'
version          '0.1.7'

supports 'ubuntu'
