name             'netplan'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Provides custom resources to install netplan and manage /etc/netplan YAML fragments'
source_url       'https://github.com/sous-chefs/netplan'
issues_url       'https://github.com/sous-chefs/netplan/issues'
chef_version     '>= 15.3'
version          '1.0.0'

supports 'debian', '>= 12.0'
supports 'ubuntu', '>= 22.04'
